## ZEPTO CAPSTONE ##

In [ ]:
from bs4 import BeautifulSoup
import requests
import random
import pandas as pd
import sqlite3

BASE_URL = "https://books.toscrape.com/"

homepage = BeautifulSoup(requests.get(BASE_URL).text, "html.parser")

category_links = homepage.select("div.side_categories ul li ul li a")

categories = []
for link in random.sample(category_links,7):
    name = link.get_text(strip=True)
    url = BASE_URL + link["href"]
    categories.append((name, url))

all_books = []

for cat_name, cat_url in categories:
    next_url = cat_url
    count = 0

    while next_url:
        response = requests.get(next_url)
        response.encoding = "utf-8"
        soup = BeautifulSoup(response.text, "html.parser")
        

        for book in soup.select("article.product_pod"):
            title = book.h3.a["title"]
            price = book.select_one("p.price_color").get_text(strip=True)
            rating = book.select_one("p.star-rating")["class"][-1]
            availability = book.select_one("p.instock.availability").get_text(strip=True)

            all_books.append({
                "title": title,
                "price": price,
                "star_rating": rating,
                "availability": availability,
                "category": cat_name,
            })
            count += 1

        nextpage = soup.select_one("li.next a")
        next_url = next_url.rsplit("/", 1)[0] + "/" + nextpage["href"] if nextpage else None

    print(f"{cat_name}: {count} books")

print(f"\nTotal books scraped: {len(all_books)}")
for b in all_books:
    print(b)

Romance: 35 books
Add a comment: 67 books
Food and Drink: 30 books
Christian Fiction: 6 books
Health: 4 books
Politics: 3 books
Religion: 7 books

Total books scraped: 152
{'title': 'Chase Me (Paris Nights #2)', 'price': '£25.27', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Black Dust', 'price': '£34.53', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Her Backup Boyfriend (The Sorensen Family #1)', 'price': '£33.97', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'First and First (Five Boroughs #3)', 'price': '£15.97', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Fifty Shades Darker (Fifty Shades #2)', 'price': '£21.96', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'The Wedding Dress', 'price': '£24.12', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Suddenly in Love (Lake Haven #1)', 'price': '£55.99', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Something More Than This', 'price': '£16.24', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Doing It Over (Most Likely To #1)', 'price': '£35.61', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': "The Wedding Pact (The O'Malleys #2)", 'price': '£32.61', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Hold Your Breath (Search and Rescue #1)', 'price': '£28.82', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Dirty (Dive Bar #1)', 'price': '£40.83', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Take Me Home Tonight (Rock Star Romance #3)', 'price': '£53.98', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Off the Hook (Fishing for Trouble #1)', 'price': '£47.67', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': "A Gentleman's Position (Society of Gentlemen #3)", 'price': '£14.75', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Sit, Stay, Love', 'price': '£20.90', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': "A Girl's Guide to Moving On (New Beginnings #2)", 'price': '£31.30', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'The Perfect Play (Play by Play #1)', 'price': '£59.99', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Dark Lover (Black Dagger Brotherhood #1)', 'price': '£12.87', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Changing the Game (Play by Play #2)', 'price': '£13.38', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'A Walk to Remember', 'price': '£56.43', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'The Purest Hook (Second Circle Tattoos #3)', 'price': '£12.25', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'The Obsession', 'price': '£45.43', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Reservations for Two', 'price': '£11.10', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': "Best of My Love (Fool's Gold #20)", 'price': '£27.41', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Where Lightning Strikes (Bleeding Stars #3)', 'price': '£39.77', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'This One Moment (Pushing Limits #1)', 'price': '£48.71', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Rhythm, Chord & Malykhin', 'price': '£28.34', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'My Perfect Mistake (Over the Top #1)', 'price': '£38.92', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Listen to Me (Fusion #1)', 'price': '£58.99', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Imperfect Harmony', 'price': '£34.74', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Fighting Fate (Fighting #6)', 'price': '£39.24', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Deep Under (Walker Security #1)', 'price': '£47.09', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Romance'}
{'title': "Charity's Cross (Charles Towne Belles #4)", 'price': '£41.24', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'Bounty (Colorado Mountain #7)', 'price': '£37.26', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Romance'}
{'title': 'The Torch Is Passed: A Harding Family Story', 'price': '£19.09', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy', 'price': '£23.89', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Art Forger', 'price': '£40.76', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'On a Midnight Clear', 'price': '£14.07', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)', 'price': '£53.90', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Shobu Samurai, Project Aryoku (#3)', 'price': '£29.06', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Modern Romance', 'price': '£28.26', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': "The White Queen (The Cousins' War #1)", 'price': '£25.91', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Song of Achilles', 'price': '£37.40', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Immortal Life of Henrietta Lacks', 'price': '£40.67', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Dovekeepers', 'price': '£48.78', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'More Than Music (Chasing the Dream #1)', 'price': '£37.61', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Code Name Verity (Code Name Verity #1)', 'price': '£22.13', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Cell', 'price': '£20.29', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Angels Walking (Angels Walking #1)', 'price': '£34.20', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer', 'price': '£56.48', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': "A People's History of the United States", 'price': '£40.79', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'A Brush of Wings (Angels Walking #3)', 'price': '£55.51', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Rook', 'price': '£37.86', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Midnight Watch: A Novel of the Titanic and the Californian', 'price': '£26.20', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore', 'price': '£59.15', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Children', 'price': '£11.88', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'One with You (Crossfire #5)', 'price': '£15.71', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Without Shame', 'price': '£48.27', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Watchmen', 'price': '£58.05', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': "A Hero's Curse (The Unseen Chronicles #1)", 'price': '£50.49', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': '23 Degrees South: A Tropical Tale of Changing Whether...', 'price': '£35.79', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Glass Castle', 'price': '£16.24', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Drowning Girls', 'price': '£35.67', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Team of Rivals: The Political Genius of Abraham Lincoln', 'price': '£20.12', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'John Adams', 'price': '£57.43', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Good in Bed (Cannie Shapiro #1)', 'price': '£37.05', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Joy of Cooking', 'price': '£43.27', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Golden Compass (His Dark Materials #1)', 'price': '£18.77', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The God Delusion', 'price': '£46.85', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Pride and Prejudice', 'price': '£19.27', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Mere Christianity', 'price': '£48.51', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Fun Home: A Family Tragicomic', 'price': '£56.59', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Raven King (The Raven Cycle #4)', 'price': '£30.57', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Find Her (Detective D.D. Warren #8)', 'price': '£22.37', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Evicted: Poverty and Profit in the American City', 'price': '£42.27', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'A Game of Thrones (A Song of Ice and Fire #1)', 'price': '£46.42', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'A Clash of Kings (A Song of Ice and Fire #2)', 'price': '£10.79', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Tipping Point: How Little Things Can Make a Big Difference', 'price': '£10.02', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Rest Is Noise: Listening to the Twentieth Century', 'price': '£34.77', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Purpose Driven Life: What on Earth Am I Here for?', 'price': '£37.19', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy #1)", 'price': '£47.80', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': "The Girl Who Kicked the Hornet's Nest (Millennium Trilogy #3)", 'price': '£57.48', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The End of Faith: Religion, Terror, and the Future of Reason', 'price': '£22.13', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Complete Poems', 'price': '£41.32', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Catcher in the Rye', 'price': '£24.55', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Case for Christ (Cases for Christianity)', 'price': '£47.84', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Blind Side: Evolution of a Game', 'price': '£53.71', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Seven Days in the Art World', 'price': '£52.33', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': "Sarah's Key", 'price': '£46.29', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Rogue Lawyer (Rogue Lawyer #1)', 'price': '£50.11', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Manuscript Found in Accra', 'price': '£34.98', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Fire Bound (Sea Haven/Sisters of the Heart #5)', 'price': '£21.28', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Cosmos', 'price': '£36.17', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': '#GIRLBOSS', 'price': '£50.96', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Sense of an Ending', 'price': '£31.38', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Republic', 'price': '£33.78', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Odyssey', 'price': '£29.64', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Light of the Fireflies', 'price': '£54.43', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Iliad', 'price': '£16.16', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'The Communist Manifesto', 'price': '£14.76', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Lord of the Flies', 'price': '£24.89', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Add a comment'}
{'title': 'Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More', 'price': '£30.52', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!', 'price': '£56.41', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'My Paris Kitchen: Recipes and Stories', 'price': '£33.37', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed', 'price': '£14.02', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Layered: Baking, Building, and Styling Spectacular Cakes', 'price': '£40.11', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us', 'price': '£37.34', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking', 'price': '£37.60', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First', 'price': '£41.25', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals', 'price': '£42.16', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Help Yourself Cookbook for Kids: 60 Easy Plant-Based Recipes Kids Can Make to Stay Healthy and Save the Earth', 'price': '£28.77', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': "It's All Easy: Healthy, Delicious Weeknight Meals in under 30 Minutes", 'price': '£19.55', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Barefoot Contessa Back to Basics', 'price': '£28.01', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': "Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again", 'price': '£50.62', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'My Kitchen Year: 136 Recipes That Saved My Life', 'price': '£11.53', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Everyday Italian: 125 Simple and Delicious Recipes', 'price': '£20.10', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'A la Mode: 120 Recipes in 60 Pairings: Pies, Tarts, Cakes, Crisps, and More Topped with Ice Cream, Gelato, Frozen Custard, and More', 'price': '£38.77', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Cravings: Recipes for What You Want to Eat', 'price': '£20.50', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York', 'price': '£12.34', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': '32 Yolks', 'price': '£53.63', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Naturally Lean: 125 Nourishing Gluten-Free, Plant-Based Recipes--All Under 300 Calories', 'price': '£11.38', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'How to Cook Everything Vegetarian: Simple Meatless Recipes for Great Food (How to Cook Everything)', 'price': '£46.01', 'star_rating': 'Four', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'How to Be a Domestic Goddess: Baking and the Art of Comfort Cooking', 'price': '£28.25', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Barefoot Contessa Cookbook', 'price': '£59.92', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Better Homes and Gardens New Cook Book', 'price': '£39.61', 'star_rating': 'Three', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Power Greens Cookbook: 140 Delicious Superfood Recipes', 'price': '£11.05', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Mexican Today: New and Rediscovered Recipes for Contemporary Kitchens', 'price': '£24.91', 'star_rating': 'Five', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'Vegan Vegetarian Omnivore: Dinner for Everyone at the Table', 'price': '£13.66', 'star_rating': 'Two', 'availability': 'In stock', 'category': 'Food and Drink'}
{'title': 'The Smitten Kitchen Cookbook', 'price': '£23.59', 'star_rating': 'One', 'availability': 'In stock', 'category': 'Food and Drink'}

In [ ]:

df = pd.DataFrame(all_books)

print(df.shape)
df

(152, 5)

,title,price,star_rating,availability,category
0,Chase Me (Paris Nights #2),£25.27,Five,In stock,Romance
1,Black Dust,£34.53,Five,In stock,Romance
2,Her Backup Boyfriend (The Sorensen Family #1),£33.97,One,In stock,Romance
3,First and First (Five Boroughs #3),£15.97,Four,In stock,Romance
4,Fifty Shades Darker (Fifty Shades #2),£21.96,One,In stock,Romance
...,...,...,...,...,...
147,God: The Most Unpleasant Character in All Fiction,£30.03,Five,In stock,Religion
148,The Book of Mormon,£24.57,Three,In stock,Religion
149,"A History of God: The 4,000-Year Quest of Juda...",£27.62,One,In stock,Religion
150,The Bhagavad Gita,£57.49,Three,In stock,Religion
151,Choosing Our Religion: The Spiritual Lives of ...,£28.42,Four,In stock,Religion

In [5]:
df['price_gbp']=df['price'].str.replace(r"[^\d.]", "", regex=True).astype(float)


rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5,
}

df["star_rating"] = df["star_rating"].map(rating_map)

In [7]:
df['in_stock']=df['availability'].str.contains('In stock',case=False,na=False)

In [8]:
price_inr=[]
for price in df['price_gbp']:
    price_value= price * 105.50
    price_inr.append(price_value)

df['price_inr']=price_inr

In [9]:
df

,title,price,star_rating,availability,category,price_gbp,in_stock,price_inr
0,Chase Me (Paris Nights #2),£25.27,5,In stock,Romance,25.27,True,2665.985
1,Black Dust,£34.53,5,In stock,Romance,34.53,True,3642.915
2,Her Backup Boyfriend (The Sorensen Family #1),£33.97,1,In stock,Romance,33.97,True,3583.835
3,First and First (Five Boroughs #3),£15.97,4,In stock,Romance,15.97,True,1684.835
4,Fifty Shades Darker (Fifty Shades #2),£21.96,1,In stock,Romance,21.96,True,2316.780
...,...,...,...,...,...,...,...,...
147,God: The Most Unpleasant Character in All Fiction,£30.03,5,In stock,Religion,30.03,True,3168.165
148,The Book of Mormon,£24.57,3,In stock,Religion,24.57,True,2592.135
149,"A History of God: The 4,000-Year Quest of Juda...",£27.62,1,In stock,Religion,27.62,True,2913.910
150,The Bhagavad Gita,£57.49,3,In stock,Religion,57.49,True,6065.195
151,Choosing Our Religion: The Spiritual Lives of ...,£28.42,4,In stock,Religion,28.42,True,2998.310

In [10]:
print(df.columns)

Index(['title', 'price', 'star_rating', 'availability', 'category',
       'price_gbp', 'in_stock', 'price_inr'],
      dtype='str')

In [ ]:


conn = sqlite3.connect("books.db")
cur = conn.cursor()

cur.execute("PRAGMA foreign_keys = ON")

cur.execute("""
CREATE TABLE categories (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name TEXT UNIQUE NOT NULL
)
""")

cur.execute("""
CREATE TABLE books (
    book_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    price REAL,
    star_rating REAL,
    availability TEXT,
    price_gbp REAL,
    in_stock INTEGER,
    price_inr REAL,
    category_id INTEGER,
    FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
)
""")

for cat in df["category"].dropna().unique():
    cur.execute(
        "INSERT INTO categories (category_name) VALUES (?)",
        (cat,)
    )

cur.execute("""
    SELECT category_id, category_name
    FROM categories
""")

category_list = {
    name: cid
    for cid, name in cur.fetchall()
}

for _, row in df.iterrows():

    cur.execute("""
        INSERT INTO books (
            title,
            price,
            star_rating,
            availability,
            price_gbp,
            in_stock,
            price_inr,
            category_id
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        row["title"],
        row["price"],
        row["star_rating"],
        row["availability"],
        row["price_gbp"],
        row["in_stock"],
        row["price_inr"],
        category_list[row["category"]]
    ))

conn.commit()

print("Database created and all data inserted successfully.")

Database created and all data inserted successfully.

In [ ]:

# Query 1: SELECT + WHERE
query1 = """
SELECT title, price_inr, star_rating
FROM books
WHERE star_rating >= 4
"""

output1 = pd.read_sql(query1, conn)


# Query 2: ORDER BY
query2 = """
SELECT title, price_inr
FROM books
ORDER BY price_inr DESC
"""

output2 = pd.read_sql(query2, conn)


# Query 3: LIMIT
query3 = """
SELECT title, star_rating
FROM books
ORDER BY star_rating DESC
LIMIT 10
"""

output3 = pd.read_sql(query3, conn)


# Query 4: DISTINCT
query4 = """
SELECT DISTINCT category_name
FROM categories
ORDER BY category_name
"""

output4 = pd.read_sql(query4, conn)


# Query 5: BETWEEN
query5 = """
SELECT title, price_inr, star_rating
FROM books
WHERE price_inr BETWEEN 500 AND 1500
ORDER BY price_inr
"""

output5 = pd.read_sql(query5, conn)


# Query 6: JOIN
query6 = """
SELECT
    b.title,
    b.star_rating,
    b.price_inr,
    c.category_name
FROM books AS b
JOIN categories AS c
    ON b.category_id = c.category_id
ORDER BY b.star_rating DESC
LIMIT 10
"""

output6 = pd.read_sql(query6, conn)

In [ ]:


queries_and_outputs = [
    ("QUERY 1 - SELECT + WHERE", query1, output1),
    ("QUERY 2 - ORDER BY", query2, output2),
    ("QUERY 3 - LIMIT", query3, output3),
    ("QUERY 4 - DISTINCT", query4, output4),
    ("QUERY 5 - BETWEEN", query5, output5),
    ("QUERY 6 - JOIN", query6, output6)
]

for name, query, output in queries_and_outputs:

    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)

    print("\nSQL:")
    print(query)

    print("\nOUTPUT:")
    print(output.to_string(index=False))

======================================================================
QUERY 1 - SELECT + WHERE
======================================================================

SQL:

SELECT title, price_inr, star_rating
FROM books
WHERE star_rating >= 4


OUTPUT:
                                                                                                                                                 title  price_inr  star_rating
                                                                                                                            Chase Me (Paris Nights #2)   2665.985          5.0
                                                                                                                                            Black Dust   3642.915          5.0
                                                                                                                    First and First (Five Boroughs #3)   1684.835          4.0
                                                                                                                              Something More Than This   1713.320          4.0
                                                                                                                                   Dirty (Dive Bar #1)   4307.565          4.0
                                                                                                      A Gentleman's Position (Society of Gentlemen #3)   1556.125          5.0
                                                                                                                                     Imperfect Harmony   3665.070          4.0
                                                                                                                       Deep Under (Walker Security #1)   4967.995          5.0
                                                                                                                         Bounty (Colorado Mountain #7)   3930.930          4.0
The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy   2520.395          4.0
                                                                                                                                        Modern Romance   2981.430          5.0
                                                                                                                 The White Queen (The Cousins' War #1)   2733.505          5.0
                                                                                                                                  The Song of Achilles   3945.700          5.0
                                                                                                                Code Name Verity (Code Name Verity #1)   2334.715          4.0
                                                                                                                                                  Cell   2140.595          4.0
                                                                                                                                                  Rook   3994.230          4.0
                                                                             The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore   6240.325          4.0
                                                                                                                           One with You (Crossfire #5)   1657.405          4.0
                                                                                                                                         Without Shame   5092.485          5.0
                                                                                                                                              Watchmen   6124.275          4.0
                                                                                               Team of Rivals: The Political Genius of Abraham Lincoln   2122.660          5.0
                                                                                                                                            John Adams   6058.865          4.0
                                                                                                                       Good in Bed (Cannie Shapiro #1)   3908.775          5.0
                                                                                                                                    The Joy of Cooking   4564.985          4.0
                                                                                                                                   Pride and Prejudice   2032.985          4.0
                                                                                                                         Fun Home: A Family Tragicomic   5970.245          4.0
                                                                                          The End of Faith: Religion, Terror, and the Future of Reason   2334.715          4.0
                                                                                                                                    The Complete Poems   4359.260          5.0
                                                                                                                   The Blind Side: Evolution of a Game   5666.405          5.0
                                                                                                        Fire Bound (Sea Haven/Sisters of the Heart #5)   2245.040          4.0
                                                                   Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed   1479.110          4.0
                                                                                    The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us   3939.370          5.0
                                                                           Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again   5340.410          5.0
                                                                                                    Everyday Italian: 125 Simple and Delicious Recipes   2120.550          5.0
                                                                           The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York   1301.870          4.0
                                                               Naturally Lean: 125 Nourishing Gluten-Free, Plant-Based Recipes--All Under 300 Calories   1200.590          5.0
                                                    How to Cook Everything Vegetarian: Simple Meatless Recipes for Great Food (How to Cook Everything)   4854.055          4.0
                                                                                                                        The Barefoot Contessa Cookbook   6321.560          5.0
                                                                                            The Power Greens Cookbook: 140 Delicious Superfood Recipes   1165.775          5.0
                                                                                 Mexican Today: New and Rediscovered Recipes for Contemporary Kitchens   2628.005          5.0
                                                                                                                                        Redeeming Love   2159.585          5.0
                                                                                                                                          Close to You   5218.030          4.0
                                                                                                                  Shadows of the Past (Logan Point #1)   4185.185          5.0
                                                                                                            Counted With the Stars (Out from Egypt #1)   1895.835          5.0
                                                                                                                                If I Run (If I Run #1)   5271.835          4.0
                                                                                       10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!   5244.405          5.0
                                                                                                        The Art and Science of Low Carbohydrate Living   5589.390          5.0
                                                                    Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond   5554.575          4.0
                                                                                                   You Are What You Love: The Spiritual Power of Habit   2307.285          4.0
                                                                                                     God: The Most Unpleasant Character in All Fiction   3168.165          5.0
                                                                                         Choosing Our Religion: The Spiritual Lives of America's Nones   2998.310          4.0

======================================================================
QUERY 2 - ORDER BY
======================================================================

SQL:

SELECT title, price_inr
FROM books
ORDER BY price_inr DESC


OUTPUT:
                                                                                                                                                                          title  price_inr
                                                                                                                                             The Perfect Play (Play by Play #1)   6328.945
                                                                                                                                                 The Barefoot Contessa Cookbook   6321.560
                                                                                                      The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore   6240.325
                                                                                                                                                       Listen to Me (Fusion #1)   6223.445
                                                                                                                                                                       Watchmen   6124.275
                                                                                                                                                              The Bhagavad Gita   6065.195
                                                                                                                  The Girl Who Kicked the Hornet's Nest (Millennium Trilogy #3)   6064.140
                                                                                                                                                                     John Adams   6058.865
                                                                                                           Equal Is Unfair: America's Misguided Fight Against Income Inequality   5998.730
                                                                                                                                                  Fun Home: A Family Tragicomic   5970.245
                                                                                               A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer   5958.640
                                                                                                                                                             A Walk to Remember   5953.365
                                                The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!   5951.255
                                                                                                                                               Suddenly in Love (Lake Haven #1)   5906.945
                                                                                                                                           A Brush of Wings (Angels Walking #3)   5856.305
                                                                                                                                                     The Light of the Fireflies   5742.365
                                                                                                                                                              Eat Fat, Get Thin   5704.385
                                                                                                                                    Take Me Home Tonight (Rock Star Romance #3)   5694.890
                                                                                                          Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)   5686.450
                                                                                                                                            The Blind Side: Evolution of a Game   5666.405
                                                                                                                                                                       32 Yolks   5657.965
                                                                                                                                 The Art and Science of Low Carbohydrate Living   5589.390
                                                                                             Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond   5554.575
                                                                                                                                                    Seven Days in the Art World   5520.815
                                                                                                                                                   Libertarianism for Beginners   5415.315
                                                                                                                                                                      #GIRLBOSS   5376.280
                                                                                                    Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again   5340.410
                                                                                                                                      A Hero's Curse (The Unseen Chronicles #1)   5326.695
                                                                                                                                                 Rogue Lawyer (Rogue Lawyer #1)   5286.605
                                                                                                                                                         If I Run (If I Run #1)   5271.835
                                                                                                                10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!   5244.405
                                                                                                                                                                   Close to You   5218.030
                                                                                    The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life   5174.775
                                                                                                                                                                The Dovekeepers   5146.290
                                                                                                                                            This One Moment (Pushing Limits #1)   5138.905
                                                                                                                                                              Mere Christianity   5117.805
                                                                                                                                                                  Without Shame   5092.485
                                                                                                                                   The Case for Christ (Cases for Christianity)   5047.120
                                                                                                     The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy #1)   5042.900
                                                                                                                                          Off the Hook (Fishing for Trouble #1)   5029.185
                                                                                                                                                Deep Under (Walker Security #1)   4967.995
                                                                                                                                                               The God Delusion   4942.675
                                                                                                                                  A Game of Thrones (A Song of Ice and Fire #1)   4897.310
                                                                                                                                                                    Sarah's Key   4883.595
                                                                             How to Cook Everything Vegetarian: Simple Meatless Recipes for Great Food (How to Cook Everything)   4854.055
                                                                                                                                                                  The Obsession   4792.865
                                                                                                                                                             The Joy of Cooking   4564.985
                                                                                                                               Evicted: Poverty and Profit in the American City   4459.485
                                                                    Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals   4447.880
                                                                                                                                                             The Complete Poems   4359.260
                                                                             The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First   4351.875
                                                                                                                                      Charity's Cross (Charles Towne Belles #4)   4350.820
                                                                                                                                                            Dirty (Dive Bar #1)   4307.565
                                                                                                                                        A People's History of the United States   4303.345

In [ ]:

sql_join_result = pd.read_sql(query6, conn)

print("SQL JOIN RESULT:")
print(sql_join_result.to_string(index=False))

SQL JOIN RESULT:
                                                  title  star_rating  price_inr category_name
                             Chase Me (Paris Nights #2)          5.0   2665.985       Romance
                                             Black Dust          5.0   3642.915       Romance
       A Gentleman's Position (Society of Gentlemen #3)          5.0   1556.125       Romance
                        Deep Under (Walker Security #1)          5.0   4967.995       Romance
                                         Modern Romance          5.0   2981.430 Add a comment
                  The White Queen (The Cousins' War #1)          5.0   2733.505 Add a comment
                                   The Song of Achilles          5.0   3945.700 Add a comment
                                          Without Shame          5.0   5092.485 Add a comment
Team of Rivals: The Political Genius of Abraham Lincoln          5.0   2122.660 Add a comment
                        Good in Bed (Cannie Shapiro #1)          5.0   3908.775 Add a comment

In [ ]:

books_df = pd.read_sql("SELECT * FROM books", conn)
categories_df = pd.read_sql("SELECT * FROM categories", conn)


merge_result = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)


merge_result = merge_result[
    [
        "title",
        "star_rating",
        "price_inr",
        "category_name"
    ]
]

merge_result = (
    merge_result
    .sort_values(
        by="star_rating",
        ascending=False
    )
    .head(10)
    .reset_index(drop=True)
)

print("PANDAS MERGE RESULT:")
print(merge_result.to_string(index=False))

PANDAS MERGE RESULT:
                                                                                  title  star_rating  price_inr     category_name
                                                             Chase Me (Paris Nights #2)          5.0   2665.985           Romance
                                                                             Black Dust          5.0   3642.915           Romance
                                       A Gentleman's Position (Society of Gentlemen #3)          5.0   1556.125           Romance
Naturally Lean: 125 Nourishing Gluten-Free, Plant-Based Recipes--All Under 300 Calories          5.0   1200.590    Food and Drink
                  Mexican Today: New and Rediscovered Recipes for Contemporary Kitchens          5.0   2628.005    Food and Drink
                        10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!          5.0   5244.405            Health
                                                   Shadows of the Past (Logan Point #1)          5.0   4185.185 Christian Fiction
                                      God: The Most Unpleasant Character in All Fiction          5.0   3168.165          Religion
            Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again          5.0   5340.410    Food and Drink
                                     Everyday Italian: 125 Simple and Delicious Recipes          5.0   2120.550    Food and Drink

In [ ]:

sql_result = sql_join_result.copy()
pandas_result = merge_result.copy()

sql_result["Source"] = "SQL JOIN"
pandas_result["Source"] = "Pandas merge()"


side_by_side = pd.concat(
    [
        sql_result.add_suffix("_SQL"),
        pandas_result.add_suffix("_Pandas")
    ],
    axis=1
)

print("\n" + "=" * 100)
print("SQL JOIN vs pandas.merge()")
print("=" * 100)

print(side_by_side.to_string(index=False))

====================================================================================================
SQL JOIN vs pandas.merge()
====================================================================================================
                                              title_SQL  star_rating_SQL  price_inr_SQL category_name_SQL Source_SQL                                                                            title_Pandas  star_rating_Pandas  price_inr_Pandas category_name_Pandas  Source_Pandas
                             Chase Me (Paris Nights #2)              5.0       2665.985           Romance   SQL JOIN                                                              Chase Me (Paris Nights #2)                 5.0          2665.985              Romance Pandas merge()
                                             Black Dust              5.0       3642.915           Romance   SQL JOIN                                                                              Black Dust                 5.0          3642.915              Romance Pandas merge()
       A Gentleman's Position (Society of Gentlemen #3)              5.0       1556.125           Romance   SQL JOIN                                        A Gentleman's Position (Society of Gentlemen #3)                 5.0          1556.125              Romance Pandas merge()
                        Deep Under (Walker Security #1)              5.0       4967.995           Romance   SQL JOIN Naturally Lean: 125 Nourishing Gluten-Free, Plant-Based Recipes--All Under 300 Calories                 5.0          1200.590       Food and Drink Pandas merge()
                                         Modern Romance              5.0       2981.430     Add a comment   SQL JOIN                   Mexican Today: New and Rediscovered Recipes for Contemporary Kitchens                 5.0          2628.005       Food and Drink Pandas merge()
                  The White Queen (The Cousins' War #1)              5.0       2733.505     Add a comment   SQL JOIN                         10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!                 5.0          5244.405               Health Pandas merge()
                                   The Song of Achilles              5.0       3945.700     Add a comment   SQL JOIN                                                    Shadows of the Past (Logan Point #1)                 5.0          4185.185    Christian Fiction Pandas merge()
                                          Without Shame              5.0       5092.485     Add a comment   SQL JOIN                                       God: The Most Unpleasant Character in All Fiction                 5.0          3168.165             Religion Pandas merge()
Team of Rivals: The Political Genius of Abraham Lincoln              5.0       2122.660     Add a comment   SQL JOIN             Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again                 5.0          5340.410       Food and Drink Pandas merge()
                        Good in Bed (Cannie Shapiro #1)              5.0       3908.775     Add a comment   SQL JOIN                                      Everyday Italian: 125 Simple and Delicious Recipes                 5.0          2120.550       Food and Drink Pandas merge()